-- migrate:up
CREATE TABLE listens (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    mediaitemid TEXT NOT NULL REFERENCES media_items(id) ON DELETE CASCADE,
    total INTEGER NOT NULL DEFAULT 1,
    total_duration INTEGER NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_listened_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
);

-- migrate:down
DROP TABLE IF EXISTS listens;
