-- migrate:up
CREATE TABLE IF NOT EXISTS tunein_regions (
    guide_id TEXT PRIMARY KEY,
    text TEXT
);

INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r101216', 'Asia');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100435', 'United Arab Emirates');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100544', 'Dubai');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100297', 'Australasia');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r101356', 'Australia');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100504', 'Queensland');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r101432', 'Cairns');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r101217', 'Europe');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100295', 'Armenia');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100535', 'Yerevan');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100416', 'Spain');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r102263', 'Alicante');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r101309', 'United Kingdom');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r101556', 'Aberdeen');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r102247', 'Aberystwyth');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r101561', 'Ashkirk');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r101563', 'Ayr');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r102257', 'Barnstaple');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r101355', 'Belfast');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r101353', 'Birmingham');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r102245', 'Blackpool');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r101981', 'Brighton');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100788', 'Bristol');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r102241', 'Caernarfon');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r101354', 'Cambridge');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100786', 'Cardiff');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r101952', 'Carlisle');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r102238', 'Chelmsford');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r102252', 'Colchester');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r102255', 'Derby');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r101558', 'Derry');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r101751', 'Dorchester');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r101557', 'Dumfries');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r101562', 'Dundee');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100783', 'Edinburgh');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r102256', 'Elgin');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r102260', 'Enniskillen');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100414', 'Exeter');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r101560', 'Fort William');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100791', 'Glasgow');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r102259', 'Gloucester');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r101566', 'Guernsey');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r102249', 'Hereford');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r102244', 'Hull');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r101393', 'Inverness');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r102250', 'Ipswich');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r101532', 'Isle of Man');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r101567', 'Jersey');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100782', 'Leeds');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r101980', 'Leicester');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r102038', 'Liverpool');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100780', 'London');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r102254', 'Luton');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r102239', 'Maidstone');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100781', 'Manchester');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r101836', 'Newbury');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100784', 'Newcastle');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r102253', 'Northampton');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r101744', 'Norwich');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100787', 'Nottingham');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r101747', 'Oxford');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r102242', 'Peterborough');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r101750', 'Plymouth');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100789', 'Portsmouth-Southampton');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100790', 'Sheffield');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r101559', 'Shetland Islands');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r102251', 'Southend-on-Sea');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r102237', 'Stockton-on-Tees');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r102243', 'Stoke-on-Trent');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r101752', 'Swansea');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r102248', 'Swindon');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r102258', 'Taunton');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r102246', 'Truro');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r102240', 'Wrexham');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r101743', 'York');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r101218', 'North America');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r101227', 'Canada');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100447', 'Alberta');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100598', 'Calgary');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100594', 'Edmonton');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100453', 'British Columbia');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r101324', 'Vancouver');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100475', 'Manitoba');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100595', 'Winnipeg');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100498', 'Ontario');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r101533', 'Hamilton');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r101366', 'Oshawa-Whitby');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100596', 'Ottawa');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100597', 'Toronto');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100503', 'Quebec');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r101321', 'Montreal');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100436', 'United States');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100449', 'Alabama');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100118', 'Huntsville');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100452', 'Arizona');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100015', 'Phoenix');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100455', 'California');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100002', 'Los Angeles');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100075', 'Monterey-Salinas-Santa Cruz');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100119', 'Oxnard-Ventura');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100162', 'Palm Springs');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100028', 'Riverside-San Bernardino');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100027', 'Sacramento');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100017', 'San Diego');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100004', 'San Francisco');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100030', 'San Jose');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100199', 'Santa Barbara');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100107', 'Santa Rosa');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100088', 'Stockton');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100457', 'Colorado');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100022', 'Denver-Boulder');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100126', 'Ft. Collins-Greeley');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100458', 'Connecticut');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100117', 'Bridgeport');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100197', 'Danbury');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100108', 'New Haven');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100142', 'Stamford-Norwalk');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100459', 'DC');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100008', 'Washington');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100460', 'Delaware');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100076', 'Wilmington');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100462', 'Florida');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100012', 'Miami-Ft. Lauderdale-Hollywood');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100077', 'Sarasota-Bradenton');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100021', 'Tampa-St. Petersburg-Clearwater');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100464', 'Georgia');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100011', 'Atlanta');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100181', 'Columbus');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100468', 'Idaho');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100121', 'Boise');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100469', 'Illinois');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100003', 'Chicago');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100143', 'Peoria');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100467', 'Iowa');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100141', 'Quad Cities');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100476', 'Maryland');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100019', 'Baltimore');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100203', 'Frederick');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100474', 'Massachusetts');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100009', 'Boston');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100183', 'Cape Cod');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100172', 'New Bedford-Fall River');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100114', 'Worcester');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100478', 'Michigan');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100146', 'Ann Arbor');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100010', 'Detroit');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100479', 'Minnesota');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100016', 'Minneapolis-St. Paul');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100480', 'Missouri');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r101351', 'St. Louis');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100490', 'New Jersey');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100036', 'Middlesex-Somerset-Union');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100052', 'Monmouth-Ocean');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100113', 'Morristown');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100249', 'Sussex');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100140', 'Trenton');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r101322', 'New York');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100051', 'Buffalo-Niagara Falls');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100149', 'Hudson Valley');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100060', 'Nassau-Suffolk (Long Island)');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100001', 'New York City');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100163', 'Poughkeepsie');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100485', 'North Carolina');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100046', 'Raleigh-Durham');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100496', 'Ohio');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100035', 'Columbus');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100499', 'Oregon');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r101331', 'Bend');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100145', 'Eugene-Springfield');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100024', 'Portland');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100500', 'Pennsylvania');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100070', 'Allentown-Bethlehem');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100079', 'Harrisburg-Lebanon-Carlisle');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100115', 'Lancaster');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100006', 'Philadelphia');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100023', 'Pittsburgh');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100133', 'Reading');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100106', 'York');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100505', 'Rhode Island');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100034', 'Providence-Warwick-Pawtucket');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100506', 'South Carolina');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100090', 'Columbia');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100510', 'Tennessee');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100045', 'Nashville');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100511', 'Texas');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100005', 'Dallas-Fort Worth');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100512', 'Utah');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100032', 'Salt Lake-Ogden-Provo');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100516', 'Washington');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100014', 'Seattle-Tacoma');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100211', 'Tri-Cities');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r101219', 'South America');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100325', 'Colombia');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r102273', 'Armenia');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100718', 'Barranquilla');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r100716', 'Bogota');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r102280', 'San Juan Del Cesar');
INSERT OR IGNORE INTO tunein_regions (guide_id, text) VALUES ('r101982', 'Tunja');

-- migrate:down
DROP TABLE IF EXISTS tunein_regions;
