# Minimal MPD configuration

audio_buffer_size "8MB"

music_directory     "/music"
playlist_directory  "/data/mpd/playlists"
db_file             "/data/mpd/tag_cache"
state_file          "/data/mpd/state"
pid_file            "/var/run/mpd/pid"

user                "root"
group               "root"
bind_to_address     "$MPD_HOST"
port                "$MPD_PORT"

input {
    plugin "ffmpeg"
}

audio_output {
    type            "pulse"
    name            "PulseAudio Streamer Output"

    # This must match the PulseAudio sink name
    sink            "streamer"

    # Optional but recommended
    mixer_type      "software"   # MPD controls volume internally
    # mixer_type    "none"       # If you want MPD volume disabled
}
