context.modules = [
    # 1. The Output FIFO (Named Pipe)
    {   name = libpipewire-module-pipe-tunnel
        args = {
            tunnel.mode = capture 
            pipe.filename = "/tmp/outputstream"
            stream.props = {
                node.name = "output-pipe"
                audio.format = "$AUDIO_FORMAT"
                audio.rate = $AUDIO_RATE
                audio.channels = $AUDIO_CHANNELS
                audio.position = "$AUDIO_POSITION"
                media.class = "Audio/Sink"
                node.description = "FIFO Output Stream"
                resample.quality = 4
                # 'node.latency' can help prevent stuttering (1024/48000 approx 21ms)
                node.latency = "4096/$AUDIO_RATE"
                target.node = "dsp-output"
            }
        }
    }

    # 2. Input Sink: librespot
    {   name = libpipewire-module-loopback
        args = {
            node.name = "librespot_loopback"
            capture.props = {
                media.class = "Audio/Sink"
                node.name = "librespot"
                node.description = "Librespot"
                audio.format = "$AUDIO_FORMAT"
                audio.rate = $AUDIO_RATE
                audio.channels = $AUDIO_CHANNELS
                audio.position = "$AUDIO_POSITION"
                stream.capture.spa-node = true
            }
            playback.props = {
                audio.format = "$AUDIO_FORMAT"
                audio.rate = $AUDIO_RATE
                audio.channels = $AUDIO_CHANNELS
                audio.position = "$AUDIO_POSITION"
                # Attempt to link to the pipe
                target.node = "dsp-input"
                target.object  = "dsp-input"
                node.autoconnect = true 
                node.dont-reconnect = true
                stream.playback.spa-node = true
            }
        }
    }

    # 3. Input Sink: streamer
    {   name = libpipewire-module-loopback
        args = {
            node.name = "streamer_loopback"
            capture.props = {
                media.class = "Audio/Sink"
                node.name = "streamer"
                node.description = "Streamer"
                audio.format = "$AUDIO_FORMAT"
                audio.rate = $AUDIO_RATE
                audio.channels = $AUDIO_CHANNELS
                audio.position = "$AUDIO_POSITION"
                stream.capture.spa-node = true
            }
            playback.props = {
                audio.format = "$AUDIO_FORMAT"
                audio.rate = $AUDIO_RATE
                audio.channels = $AUDIO_CHANNELS
                audio.position = "$AUDIO_POSITION"
                target.object  = "dsp-input"
                target.node = "dsp-input"
                node.autoconnect = true 
                node.dont-reconnect = true
                stream.playback.spa-node = true
            }
        }
    }

    # 4. HTTP Bridge Sink
    {   name = libpipewire-module-loopback
        args = {
            node.name = "http_loopback"
            capture.props = {
                node.name = "http-input-bridge"
                target.object = "dsp-output"
                node.autoconnect = true
                stream.capture.spa-node = true
            }
            playback.props = {
                media.class = "Audio/Sink"
                node.name = "output-http"
                node.description = "HTTP Stream Sink"
                audio.format = "$AUDIO_FORMAT"
                audio.rate = $AUDIO_RATE
                audio.channels = $AUDIO_CHANNELS
                audio.position = "$AUDIO_POSITION"
                node.passive = true
            }
        }
    }


]
