monitor.bluez.properties = {
    bluez5.enable-sbc-xq = false,
    bluez5.enable-msbc = false,
    bluez5.enable-hw-volume = false,
}
# Or more effectively, simply don't load the monitor in main.lua.d
